# Generated by Django 2.1.3 on 2018-12-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('envName', models.CharField(max_length=20)),
                ('TestModel', models.CharField(max_length=20)),
                ('email1', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('email3', models.CharField(max_length=100)),
                ('TestTime', models.CharField(max_length=20)),
                ('autopush', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='envinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='envinfo',
            name='Name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
