# Generated by Django 2.1.3 on 2018-12-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_setting', '0003_auto_20181220_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rfrecord',
        ),
    ]
