# Generated by Django 2.1.3 on 2018-12-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_setting', '0005_rfrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rfrecord',
        ),
    ]
